services:
  couchdb:
    image: couchdb:3
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb_data:/opt/couchdb/data

  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - couchdb
    restart: on-failure
    environment:
      - COUCHDB_HOST=http://couchdb:5984/
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password

volumes:
  couchdb_data:
