version: '3.9'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt
    environment:
      NEO4J_AUTH: "neo4j/test"   # Benutzer: neo4j, Passwort: test
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
