services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    container_name: fastapi_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - mongodb
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: flask_web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
    depends_on:
      - api
    environment:
      # Ändere die URL hier, damit sie vom Browser aus erreichbar ist
      - API_URL=http://localhost:8000

volumes:
  mongo_data:
